/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ChatUpdateManyWithoutCompaniesInput } from "./ChatUpdateManyWithoutCompaniesInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { InterviewUpdateManyWithoutCompaniesInput } from "./InterviewUpdateManyWithoutCompaniesInput";
import { JobUpdateManyWithoutCompaniesInput } from "./JobUpdateManyWithoutCompaniesInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class CompanyUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ChatUpdateManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => ChatUpdateManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => ChatUpdateManyWithoutCompaniesInput, {
    nullable: true,
  })
  chats?: ChatUpdateManyWithoutCompaniesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  companySize?: string | null;

  @ApiProperty({
    required: false,
    type: () => InterviewUpdateManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => InterviewUpdateManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => InterviewUpdateManyWithoutCompaniesInput, {
    nullable: true,
  })
  interviews?: InterviewUpdateManyWithoutCompaniesInput;

  @ApiProperty({
    required: false,
    type: () => JobUpdateManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => JobUpdateManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => JobUpdateManyWithoutCompaniesInput, {
    nullable: true,
  })
  jobs?: JobUpdateManyWithoutCompaniesInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  logo?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  recruiter?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  sector?: string | null;
}

export { CompanyUpdateInput as CompanyUpdateInput };
