/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ChatCreateNestedManyWithoutCompaniesInput } from "./ChatCreateNestedManyWithoutCompaniesInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { InterviewCreateNestedManyWithoutCompaniesInput } from "./InterviewCreateNestedManyWithoutCompaniesInput";
import { JobCreateNestedManyWithoutCompaniesInput } from "./JobCreateNestedManyWithoutCompaniesInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class CompanyCreateInput {
  @ApiProperty({
    required: false,
    type: () => ChatCreateNestedManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => ChatCreateNestedManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => ChatCreateNestedManyWithoutCompaniesInput, {
    nullable: true,
  })
  chats?: ChatCreateNestedManyWithoutCompaniesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  companySize?: string | null;

  @ApiProperty({
    required: false,
    type: () => InterviewCreateNestedManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => InterviewCreateNestedManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => InterviewCreateNestedManyWithoutCompaniesInput, {
    nullable: true,
  })
  interviews?: InterviewCreateNestedManyWithoutCompaniesInput;

  @ApiProperty({
    required: false,
    type: () => JobCreateNestedManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => JobCreateNestedManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => JobCreateNestedManyWithoutCompaniesInput, {
    nullable: true,
  })
  jobs?: JobCreateNestedManyWithoutCompaniesInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  logo?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  recruiter?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  sector?: string | null;
}

export { CompanyCreateInput as CompanyCreateInput };
